<?php

namespace Container4xCMzub;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SpYfVsxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SpYfVsx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SpYfVsx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reclamationRepository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'session' => ['privates', '.errored.IAkfHor', NULL, 'Cannot determine controller argument for "App\\Controller\\ReclamationController::Ban()": the $session argument is type-hinted with the non-existent class or interface: "App\\Controller\\SessionInterface". Did you forget to add a use statement?'],
            'user' => ['privates', '.errored..service_locator.SpYfVsx.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.SpYfVsx": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
            'userrepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'reclamationRepository' => 'App\\Repository\\ReclamationRepository',
            'session' => '?',
            'user' => 'App\\Entity\\Utilisateur',
            'userrepo' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
