<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7wPYgPP\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7wPYgPP/App_KernelDevContainer.php') {
    touch(__DIR__.'/Container7wPYgPP.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\Container7wPYgPP\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \Container7wPYgPP\App_KernelDevContainer([
    'container.build_hash' => '7wPYgPP',
    'container.build_id' => 'c2a0dad9',
    'container.build_time' => 1678993375,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7wPYgPP');
