<?php

namespace ContainerLibXBrs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YTR610BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yTR610B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yTR610B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reponse' => ['privates', '.errored..service_locator.yTR610B.App\\Entity\\Reponse', NULL, 'Cannot autowire service ".service_locator.yTR610B": it references class "App\\Entity\\Reponse" but no such service exists.'],
            'userrepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'reponse' => 'App\\Entity\\Reponse',
            'userrepo' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
