<?php

namespace ContainerLibXBrs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LaUxRHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LaUx_rH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LaUx_rH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reclamationRepository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.LaUx_rH.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.LaUx_rH": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
            'userrepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'reclamationRepository' => 'App\\Repository\\ReclamationRepository',
            'user' => 'App\\Entity\\Utilisateur',
            'userrepo' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
