<?php

namespace ContainerCL0HIzw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8oPCjJfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8oPCjJf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8oPCjJf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\SecurityController::goDashboard' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\SecurityController::goHome' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.v5RpKZt', 'get_ServiceLocator_V5RpKZtService', true],
            'App\\Controller\\UtilisateurController::delete' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController::edit' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController::editProfile' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController::index' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\UtilisateurController::newA' => ['privates', '.service_locator.zijaqOh', 'get_ServiceLocator_ZijaqOhService', true],
            'App\\Controller\\UtilisateurController::newE' => ['privates', '.service_locator.zijaqOh', 'get_ServiceLocator_ZijaqOhService', true],
            'App\\Controller\\UtilisateurController::newF' => ['privates', '.service_locator.rYPGZXN', 'get_ServiceLocator_RYPGZXNService', true],
            'App\\Controller\\UtilisateurController::saveImg' => ['privates', '.service_locator.ACzwQ3h', 'get_ServiceLocator_ACzwQ3hService', true],
            'App\\Controller\\UtilisateurController::show' => ['privates', '.service_locator.r5W7ygF', 'get_ServiceLocator_R5W7ygFService', true],
            'App\\Controller\\UtilisateurController::showFront' => ['privates', '.service_locator.r5W7ygF', 'get_ServiceLocator_R5W7ygFService', true],
            'App\\Controller\\UtilisateurController::verifyUserEmail' => ['privates', '.service_locator.ACzwQ3h', 'get_ServiceLocator_ACzwQ3hService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\SecurityController:goDashboard' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\SecurityController:goHome' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.v5RpKZt', 'get_ServiceLocator_V5RpKZtService', true],
            'App\\Controller\\UtilisateurController:delete' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController:edit' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController:editProfile' => ['privates', '.service_locator.KzL3gdR', 'get_ServiceLocator_KzL3gdRService', true],
            'App\\Controller\\UtilisateurController:index' => ['privates', '.service_locator.JMejbpE', 'get_ServiceLocator_JMejbpEService', true],
            'App\\Controller\\UtilisateurController:newA' => ['privates', '.service_locator.zijaqOh', 'get_ServiceLocator_ZijaqOhService', true],
            'App\\Controller\\UtilisateurController:newE' => ['privates', '.service_locator.zijaqOh', 'get_ServiceLocator_ZijaqOhService', true],
            'App\\Controller\\UtilisateurController:newF' => ['privates', '.service_locator.rYPGZXN', 'get_ServiceLocator_RYPGZXNService', true],
            'App\\Controller\\UtilisateurController:saveImg' => ['privates', '.service_locator.ACzwQ3h', 'get_ServiceLocator_ACzwQ3hService', true],
            'App\\Controller\\UtilisateurController:show' => ['privates', '.service_locator.r5W7ygF', 'get_ServiceLocator_R5W7ygFService', true],
            'App\\Controller\\UtilisateurController:showFront' => ['privates', '.service_locator.r5W7ygF', 'get_ServiceLocator_R5W7ygFService', true],
            'App\\Controller\\UtilisateurController:verifyUserEmail' => ['privates', '.service_locator.ACzwQ3h', 'get_ServiceLocator_ACzwQ3hService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::goDashboard' => '?',
            'App\\Controller\\SecurityController::goHome' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UtilisateurController::delete' => '?',
            'App\\Controller\\UtilisateurController::edit' => '?',
            'App\\Controller\\UtilisateurController::editProfile' => '?',
            'App\\Controller\\UtilisateurController::index' => '?',
            'App\\Controller\\UtilisateurController::newA' => '?',
            'App\\Controller\\UtilisateurController::newE' => '?',
            'App\\Controller\\UtilisateurController::newF' => '?',
            'App\\Controller\\UtilisateurController::saveImg' => '?',
            'App\\Controller\\UtilisateurController::show' => '?',
            'App\\Controller\\UtilisateurController::showFront' => '?',
            'App\\Controller\\UtilisateurController::verifyUserEmail' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:goDashboard' => '?',
            'App\\Controller\\SecurityController:goHome' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UtilisateurController:delete' => '?',
            'App\\Controller\\UtilisateurController:edit' => '?',
            'App\\Controller\\UtilisateurController:editProfile' => '?',
            'App\\Controller\\UtilisateurController:index' => '?',
            'App\\Controller\\UtilisateurController:newA' => '?',
            'App\\Controller\\UtilisateurController:newE' => '?',
            'App\\Controller\\UtilisateurController:newF' => '?',
            'App\\Controller\\UtilisateurController:saveImg' => '?',
            'App\\Controller\\UtilisateurController:show' => '?',
            'App\\Controller\\UtilisateurController:showFront' => '?',
            'App\\Controller\\UtilisateurController:verifyUserEmail' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
