<?php

namespace ContainerBZ9FpzY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JUGNbr3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JUGNbr3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JUGNbr3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\MessagerieController::message_pusher' => ['privates', '.service_locator.jGLE8BW', 'get_ServiceLocator_JGLE8BWService', true],
            'App\\Controller\\MessagerieController::sendMessage' => ['privates', '.service_locator.lWxSJ_W', 'get_ServiceLocator_LWxSJWService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\MessagerieController:message_pusher' => ['privates', '.service_locator.jGLE8BW', 'get_ServiceLocator_JGLE8BWService', true],
            'App\\Controller\\MessagerieController:sendMessage' => ['privates', '.service_locator.lWxSJ_W', 'get_ServiceLocator_LWxSJWService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\MessagerieController::message_pusher' => '?',
            'App\\Controller\\MessagerieController::sendMessage' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MessagerieController:message_pusher' => '?',
            'App\\Controller\\MessagerieController:sendMessage' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
