<?php

namespace ContainerBZ9FpzY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LWxSJWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lWxSJ_W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lWxSJ_W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'convo' => ['privates', '.errored..service_locator.lWxSJ_W.App\\Entity\\Conversation', NULL, 'Cannot autowire service ".service_locator.lWxSJ_W": it references class "App\\Entity\\Conversation" but no such service exists.'],
            'man' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'convo' => 'App\\Entity\\Conversation',
            'man' => '?',
        ]);
    }
}
