<?php

namespace ContainerBZ9FpzY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConversationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lWxSJ_W.App\Entity\Conversation' shared service.
     *
     * @return \App\Entity\Conversation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.lWxSJ_W": it references class "App\\Entity\\Conversation" but no such service exists.');
    }
}
