<?php

namespace ContainerBZ9FpzY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipantRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ParticipantRepository' shared autowired service.
     *
     * @return \App\Repository\ParticipantRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'ParticipantRepository.php';

        return $container->privates['App\\Repository\\ParticipantRepository'] = new \App\Repository\ParticipantRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
