<?php

namespace ContainerBZ9FpzY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPusherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pusher\Pusher' shared service.
     *
     * @return \Pusher\Pusher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pusher'.\DIRECTORY_SEPARATOR.'pusher-php-server'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'PusherInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pusher'.\DIRECTORY_SEPARATOR.'pusher-php-server'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Pusher.php';

        return $container->services['Pusher\\Pusher'] = new \Pusher\Pusher($container->getEnv('PUSHER_KEY'), $container->getEnv('PUSHER_SECRET'), $container->getEnv('PUSHER_APP_ID'));
    }
}
