<?php

namespace ContainerJV8h95G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YrOaVlOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YrOaVlO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YrOaVlO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cr' => ['privates', 'App\\Repository\\ConversationRepository', 'getConversationRepositoryService', false],
            'man' => ['services', 'doctrine', 'getDoctrineService', false],
            'mr' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'pr' => ['privates', 'App\\Repository\\ParticipantRepository', 'getParticipantRepositoryService', true],
            'ur' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'cr' => 'App\\Repository\\ConversationRepository',
            'man' => '?',
            'mr' => 'App\\Repository\\MessageRepository',
            'pr' => 'App\\Repository\\ParticipantRepository',
            'ur' => 'App\\Repository\\UserRepository',
        ]);
    }
}
